SETTING_FILENAME = 'filename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_PAINT_LABEL = 'paintlabel'
SETTING_LAST_OPEN_DIR = 'lastOpenDir'
SETTING_AUTO_SAVE = 'autosave'
SETTING_DRAW_CORNER = 'drawcorner'
SETTING_SINGLE_CLASS = 'singleclass'
SETTING_DEFAULT_LABEL = 'defaultlabel'
SETTING_LABEL_USAGE = 'labelusage'
SETTING_ANNOTATION_FORMAT = 'annotationformat'

FORMAT_PASCALVOC = 'xml'
FORMAT_YOLO = 'yolo'
FORMAT_YOLO_OBB = 'yolo_obb'
SUPPORTED_ANNOTATION_FORMATS = (
    FORMAT_PASCALVOC,
    FORMAT_YOLO,
    FORMAT_YOLO_OBB,
)
